name       : stress-ng
version    : 0.08.10
release    : 3
source     :
    - http://kernel.ubuntu.com/~cking/tarballs/stress-ng/stress-ng-0.08.10.tar.gz : f2465f788ce297a9ea496df3b6084ee6835836d15c118a07d26273a977cdcd12
license    : GPL-2.0
component  : system.utils
summary    : stress-ng will stress test a computer system in various selectable ways
description: |
    stress-ng will stress test a computer system in various selectable ways
build      : |
    %make
install    : |
    %make_install
