name       : stress-ng
version    : 0.13.05
release    : 11
source     :
    - https://kernel.ubuntu.com/~cking/tarballs/stress-ng/stress-ng-0.13.05.tar.xz : f058c8fba37596ab32c3a4b2aedbdbf5f2b8a8ba1d312059e733290543ad00ac
license    : GPL-2.0-or-later
component  : system.utils
homepage   : https://kernel.ubuntu.com/~cking/stress-ng/
summary    : Multi-option stress test utility
description: |
    stress-ng will stress test a computer system in various selectable ways. It was designed to exercise various physical subsystems of a computer as well as the various operating system kernel interfaces.
clang      : yes
optimize   :
    - thin-lto
build      : |
    %make
install    : |
    %make_install
