name       : stress-ng
version    : 0.09.48
release    : 5
source     :
    - http://kernel.ubuntu.com/~cking/tarballs/stress-ng/stress-ng-0.09.48.tar.xz : ed5542b2915b185949652f113bf35e9fd74175ab364de27109846bdc9df1d9fe
license    : GPL-2.0-or-later
component  : system.utils
summary    : stress-ng will stress test a computer system in various selectable ways
description: |
    stress-ng will stress test a computer system in various selectable ways
build      : |
    %make
install    : |
    %make_install
