name       : stress-ng
version    : 0.07.13
release    : 1
source     :
    - http://kernel.ubuntu.com/~cking/tarballs/stress-ng/stress-ng-0.07.13.tar.gz : 1fc8e60653ab75f288ce58b63ed162eedda2d5a2b254f0ad47ed6283deeddfe8
license    : GPL-2.0
component  : system.utils
summary    : stress-ng will stress test a computer system in various selectable ways
description: |
    stress-ng will stress test a computer system in various selectable ways
build      : |
    %make
install    : |
    %make_install
