name       : stress-ng
version    : 0.13.00
release    : 10
source     :
    - https://kernel.ubuntu.com/~cking/tarballs/stress-ng/stress-ng-0.13.00.tar.xz : 1cefe4a3057c1522b146e62f61b80ce6e2e99da2d85ebe25bc03fc45228e58cd
license    : GPL-2.0-or-later
component  : system.utils
homepage   : https://kernel.ubuntu.com/~cking/stress-ng/
summary    : Multi-option stress test utility
description: |
    stress-ng will stress test a computer system in various selectable ways. It was designed to exercise various physical subsystems of a computer as well as the various operating system kernel interfaces.
clang      : yes
optimize   :
    - thin-lto
build      : |
    %make
install    : |
    %make_install
