name       : stress-ng
version    : 0.08.05
release    : 2
source     :
    - http://kernel.ubuntu.com/~cking/tarballs/stress-ng/stress-ng-0.08.05.tar.gz : 8a7508ca9f0ee25f91ad3b5040550c00dbc8300f47c4e945463dcfcd93543a60
license    : GPL-2.0
component  : system.utils
summary    : stress-ng will stress test a computer system in various selectable ways
description: |
    stress-ng will stress test a computer system in various selectable ways
build      : |
    %make
install    : |
    %make_install
