name       : stress-ng
version    : 0.12.12
release    : 9
source     :
    - https://kernel.ubuntu.com/~cking/tarballs/stress-ng/stress-ng-0.12.12.tar.xz : f27af50f6f2308e707fef927674bdd209a046b116734281b792aeca35a4e4499
license    : GPL-2.0-or-later
component  : system.utils
homepage   : https://kernel.ubuntu.com/~cking/stress-ng/
summary    : Multi-option stress test utility
description: |
    stress-ng will stress test a computer system in various selectable ways. It was designed to exercise various physical subsystems of a computer as well as the various operating system kernel interfaces.
build      : |
    %make
install    : |
    %make_install
