name       : stress-ng
version    : 0.12.09
release    : 8
source     :
    - https://kernel.ubuntu.com/~cking/tarballs/stress-ng/stress-ng-0.12.09.tar.xz : cffac091082c7adbfec649be3c66941c3d622f8b96795656bcce2e20d669cfeb
license    : GPL-2.0-or-later
component  : system.utils
homepage   : https://kernel.ubuntu.com/~cking/stress-ng/
summary    : Multi-option stress test utility
description: |
    stress-ng will stress test a computer system in various selectable ways. It was designed to exercise various physical subsystems of a computer as well as the various operating system kernel interfaces.
build      : |
    %make
install    : |
    %make_install
