name       : stress-ng
version    : 0.09.38
release    : 4
source     :
    - http://kernel.ubuntu.com/~cking/tarballs/stress-ng/stress-ng-0.09.38.tar.xz : 4cd3c1f24d099e6fe507a9fcddd8aafdf13be447d811db9e37b5e25c952bf20c
license    : GPL-2.0-or-later
component  : system.utils
summary    : stress-ng will stress test a computer system in various selectable ways
description: |
    stress-ng will stress test a computer system in various selectable ways
build      : |
    %make
install    : |
    %make_install
