name       : stress-ng
version    : 0.13.05
release    : 12
source     :
    - https://github.com/ColinIanKing/stress-ng/archive/refs/tags/V0.13.05.tar.gz : 3de49e1100866634f549e99c1644283d0cde817b844a69dcf7f80afa2227d350
license    : GPL-2.0-or-later
component  : system.utils
homepage   : https://kernel.ubuntu.com/~cking/stress-ng/
summary    : Multi-option stress test utility
description: |
    stress-ng will stress test a computer system in various selectable ways. It was designed to exercise various physical subsystems of a computer as well as the various operating system kernel interfaces.
clang      : yes
optimize   :
    - thin-lto
build      : |
    %make
install    : |
    %make_install
