name       : stress-ng
version    : 0.10.08
release    : 6
source     :
    - https://github.com/ColinIanKing/stress-ng/archive/V0.10.08.tar.gz : a683eeff25e41c1e52d52479ffedaa382a7f14361dd6227da64633d2cca336ef
license    : GPL-2.0-or-later
component  : system.utils
summary    : stress-ng will stress test a computer system in various selectable ways
description: |
    stress-ng will stress test a computer system in various selectable ways
build      : |
    %make
install    : |
    %make_install
